/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:10a62a35-fb18-44a5-a002-98eda874ed0a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_7gnjW3611",
    "aws_user_pools_web_client_id": "612m7bhde16g921o83g4jgh7p2",
    "oauth": {},
    "aws_bots": "enable",
    "aws_bots_config": [
        {
            "name": "BookTrip_dev",
            "alias": "$LATEST",
            "region": "us-east-1"
        }
    ],
    "aws_user_files_s3_bucket": "travelbuddy-profileimgstore131246-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
